package com.evizone.pkiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-05-27T12:01:42.710+02:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://pkiservice.evizone.com/", name = "OpenXPKI")
@XmlSeeAlso({ObjectFactory.class})
public interface OpenXPKI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enroll", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.Enroll")
    @WebMethod
    @ResponseWrapper(localName = "enrollResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.EnrollResponse")
    public java.lang.String enroll(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.EnrollInput arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "poll", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.Poll")
    @WebMethod
    @ResponseWrapper(localName = "pollResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.PollResponse")
    public com.evizone.pkiservice.CsrStatus poll(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.PollInput arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.Download")
    @WebMethod
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.DownloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.PollInput arg0
    );
}
