
/*
 * 
 */

package com.evizone.pkiservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-05-27T12:01:42.770+02:00
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "OpenXPKIService", 
                  wsdlLocation = "${openxpkiServiceUrl}",
                  targetNamespace = "http://pkiservice.evizone.com/") 
public class OpenXPKIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pkiservice.evizone.com/", "OpenXPKIService");
    public final static QName OpenXPKIPort = new QName("http://pkiservice.evizone.com/", "OpenXPKIPort");
    static {
        URL url = null;
        try {
            url = new URL("${openxpkiServiceUrl}");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://127.0.0.1:8080/pkiservice/OpenXPKIService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public OpenXPKIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpenXPKIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenXPKIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     * 
     * @return
     *     returns OpenXPKI
     */
    @WebEndpoint(name = "OpenXPKIPort")
    public OpenXPKI getOpenXPKIPort() {
        return super.getPort(OpenXPKIPort, OpenXPKI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenXPKI
     */
    @WebEndpoint(name = "OpenXPKIPort")
    public OpenXPKI getOpenXPKIPort(WebServiceFeature... features) {
        return super.getPort(OpenXPKIPort, OpenXPKI.class, features);
    }

}
