package com.evizone.pkiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-05-19T14:00:17.761+02:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://pkiservice.evizone.com/", name = "Authorization")
@XmlSeeAlso({ObjectFactory.class})
public interface Authorization {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.RegisterResponse")
    public java.lang.String register(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.User arg0
    );
}
