package com.evizone.pkiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-05-27T16:24:01.679+02:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://pkiservice.evizone.com/", name = "Authorization")
@XmlSeeAlso({ObjectFactory.class})
public interface Authorization {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "openxpkiRegister", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.OpenxpkiRegister")
    @WebMethod
    @ResponseWrapper(localName = "openxpkiRegisterResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.OpenxpkiRegisterResponse")
    public java.lang.String openxpkiRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ejbcaRegister", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.EjbcaRegister")
    @WebMethod
    @ResponseWrapper(localName = "ejbcaRegisterResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.EjbcaRegisterResponse")
    public java.lang.String ejbcaRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.User arg0
    );
}
