package com.evizone.pkiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-05-19T13:59:29.967+02:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://pkiservice.evizone.com/", name = "EJBCA")
@XmlSeeAlso({ObjectFactory.class})
public interface EJBCA {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.RegisterResponse")
    public java.lang.String register(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.RegisterInput arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enrollAndGetCert", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.EnrollAndGetCert")
    @WebMethod
    @ResponseWrapper(localName = "enrollAndGetCertResponse", targetNamespace = "http://pkiservice.evizone.com/", className = "com.evizone.pkiservice.EnrollAndGetCertResponse")
    public byte[] enrollAndGetCert(
        @WebParam(name = "arg0", targetNamespace = "")
        com.evizone.pkiservice.EnrollAndGetCertInput arg0,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arg1", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> arg1
    );
}
