
/*
 * 
 */

package com.evizone.pkiservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2014-05-19T13:59:30.047+02:00
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "EJBCAService", 
                  wsdlLocation = "${ejbcaServiceUrl}",
                  targetNamespace = "http://pkiservice.evizone.com/") 
public class EJBCAService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pkiservice.evizone.com/", "EJBCAService");
    public final static QName EJBCAPort = new QName("http://pkiservice.evizone.com/", "EJBCAPort");
    static {
        URL url = null;
        try {
            url = new URL("${ejbcaServiceUrl}");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from ${ejbcaServiceUrl}");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EJBCAService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EJBCAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EJBCAService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     * 
     * @return
     *     returns EJBCA
     */
    @WebEndpoint(name = "EJBCAPort")
    public EJBCA getEJBCAPort() {
        return super.getPort(EJBCAPort, EJBCA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EJBCA
     */
    @WebEndpoint(name = "EJBCAPort")
    public EJBCA getEJBCAPort(WebServiceFeature... features) {
        return super.getPort(EJBCAPort, EJBCA.class, features);
    }

}
